// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: woocommerce.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWooProduct = `-- name: CreateWooProduct :one
INSERT INTO woocommerce(
    id,
    title,
    sku,
    price,
    qty,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, sku, price, qty, created_at, updated_at
`

type CreateWooProductParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Sku       string    `json:"sku"`
	Price     string    `json:"price"`
	Qty       int32     `json:"qty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateWooProduct(ctx context.Context, arg CreateWooProductParams) (Woocommerce, error) {
	row := q.db.QueryRowContext(ctx, createWooProduct,
		arg.ID,
		arg.Title,
		arg.Sku,
		arg.Price,
		arg.Qty,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Woocommerce
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Sku,
		&i.Price,
		&i.Qty,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchWooProductBySKU = `-- name: SearchWooProductBySKU :many
SELECT id, title, sku, price, qty, created_at, updated_at FROM woocommerce
WHERE "sku" SIMILAR TO $1
`

func (q *Queries) SearchWooProductBySKU(ctx context.Context, similarToEscape string) ([]Woocommerce, error) {
	rows, err := q.db.QueryContext(ctx, searchWooProductBySKU, similarToEscape)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Woocommerce
	for rows.Next() {
		var i Woocommerce
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Sku,
			&i.Price,
			&i.Qty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchWooProductByTitle = `-- name: SearchWooProductByTitle :many
SELECT id, title, sku, price, qty, created_at, updated_at FROM woocommerce
WHERE "title" SIMILAR TO $1
`

func (q *Queries) SearchWooProductByTitle(ctx context.Context, similarToEscape string) ([]Woocommerce, error) {
	rows, err := q.db.QueryContext(ctx, searchWooProductByTitle, similarToEscape)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Woocommerce
	for rows.Next() {
		var i Woocommerce
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Sku,
			&i.Price,
			&i.Qty,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
