version: "2"
services:
    web:
        build: .
        ports:
            - "8000:${PORT}"
        container_name: blog_aggregator
        env_file:
            - .env
    database:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - db-volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PSW}
volumes:
    db-volume:
        driver: local
